language: python
python:
  - 2.7.10

sudo: false

branches:
  except:
    - master

install: pip install -U pyOpenSSL

cache: pip

before_script:
 - chmod +x ./tests/all_tests.py

script:
  - ./tests/all_tests.py

after_failure:
  - cat ./Logs/sickrage.log

notifications:
  irc: "irc.freenode.net#sickrage-updates"

  email:
    on_success: change
    on_failure: change
